altruist:
  dashboard:
    enabled: true

  environment:
    mode: "3D"

  security:
    mode: "jwt"

  server:
    http:
      host: "0.0.0.0"
      port: 8000
      path: "/"
    transport:
      mode: websocket
      timeout: 60
      codec:
        provider: json
      config:
        path: "ws"

  persistence:
    database:
      provider: postgres
      host: localhost
      port: 5432
      username: altruist
      password: altruist
      database: altruist
    cache:
      provider: "inmemory"

  game:
    engine:
      diagnostics: true
      frequency: 30
      unit: "ticks"
      gravity: { x: 0, y: -9.81 }
    worlds:
      partitioner: { width: 256, height: 256, depth: 256 }
      items:
        - index: 0
          id: "world1"
          data-path: "Resources/world.json"
          size: { x: 100, y: 100, z: 100 }
          gravity: { x: 0, y: -9.81 }
          position: { x: 0, y: 0, z: 0 }
